/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPayfastItnRouteImport } from './routes/api/public/payfast-itn'

const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayfastItnRoute = ApiPublicPayfastItnRouteImport.update({
  id: '/api/public/payfast-itn',
  path: '/api/public/payfast-itn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/refund-policy' | '/api/public/payfast-itn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/refund-policy' | '/api/public/payfast-itn'
  id: '__root__' | '/' | '/about' | '/refund-policy' | '/api/public/payfast-itn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ApiPublicPayfastItnRoute: typeof ApiPublicPayfastItnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payfast-itn': {
      id: '/api/public/payfast-itn'
      path: '/api/public/payfast-itn'
      fullPath: '/api/public/payfast-itn'
      preLoaderRoute: typeof ApiPublicPayfastItnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ApiPublicPayfastItnRoute: ApiPublicPayfastItnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
